<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Low Stock Report</title>

    <style>
        body{
            font-family: DejaVu Sans, sans-serif;
            font-size:12px;
        }

        table{
            width:100%;
            border-collapse:collapse;
            margin-top:20px;
        }

        table, th, td{
            border:1px solid black;
        }

        th, td{
            padding:8px;
            text-align:left;
        }

        h2, h3, h4{
            text-align:center;
            margin:0;
        }

        hr{
            margin:15px 0;
        }
    </style>
</head>
<body>

<h2>BizzSoft Solutions</h2>
<h3>Inventory Management System</h3>
<h4>Low Stock Report</h4>

<hr>

<p>
    <strong>Date Generated:</strong>
    {{ now()->format('F d, Y h:i A') }}
</p>

<p>
    <strong>Report Period:</strong>
    Items Requiring Reorder
</p>

<table>
    <thead>
        <tr>
            <th>No.</th>
            <th>Product Name</th>
            <th>Category</th>
            <th>Reorder Level</th>
            <th>Current Stock</th>
        </tr>
    </thead>
    
    <tbody>
        @foreach($lowStockProducts as $product)
        <tr>
            <td>{{ $loop->iteration }}</td>
            <td>{{ $product->name }}</td>
            <td>{{ $product->category->category_name ?? 'N/A' }}</td>
            <td>{{ $product->reorder_level }}</td>
            <td style="color: red; font-weight: bold;">{{ $product->stock }}</td>
        </tr>
        @endforeach
    </tbody>
</table>

<br>
<hr>

<h4>Report Summary</h4>

<table>
    <tr>
        <td><strong>Total Low Stock Items</strong></td>
        <td>{{ $totalLowStockProducts }}</td>
    </tr>
    <tr>
        <td><strong>Total Remaining Quantity</strong></td>
        <td>{{ $totalLowStockQuantity }}</td>
    </tr>
</table>

<br><br>

<p>
    Generated by:
    {{ auth()->user()->name }}
</p>

</body>
</html>
