<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Sales Report</title>

    <style>
        body{
            font-family: DejaVu Sans, sans-serif;
            font-size:12px;
        }

        table{
            width:100%;
            border-collapse:collapse;
            margin-top:20px;
        }

        table, th, td{
            border:1px solid black;
        }

        th, td{
            padding:8px;
            text-align:left;
        }

       

        h2,
        h3,
        h4{

        text-align:center;

        margin:0;

        }

        hr{

         margin:15px 0;

        }
    </style>
</head>
<body>

<h2>BizzSoft Solutions</h2>

<h3>Inventory Management System</h3>

<h4>Sales Report</h4>

<hr>

<p>
    <strong>Date Generated:</strong>
    {{ now()->format('F d, Y h:i A') }}
</p>

<p>
    <strong>Report Period:</strong>

    All Records
</p>

<table>

    <thead>

        <tr>
            <th>No.</th>
            <th>Product</th>
            <th>Quantity</th>
            <th>Selling Price</th>
            <th>Total</th>
        </tr>

    </thead>
    

    <tbody>

@foreach($sales as $sale)

<tr>

    <td>{{ $loop->iteration }}</td>

    <td>{{ $sale->product->name }}</td>

    <td>{{ $sale->quantity }}</td>

    <td>{{ number_format($sale->selling_price,2) }}</td>

    <td>{{ number_format($sale->line_total,2) }}</td>

</tr>

@endforeach

    </tbody>

</table>

<br>

<hr>

<h4>Report Summary</h4>

<table>

    <tr>

        <td><strong>Total Sales</strong></td>

        <td>{{ number_format($totalSales, 2) }}</td>

    </tr>

    <tr>

        <td><strong>Total Quantity</strong></td>

        <td>{{ $totalQuantity }}</td>

    </tr>

    <tr>

        <td><strong>Total Transactions</strong></td>

        <td>{{ $totalTransactions }}</td>

    </tr>

</table>

<br><br>

<p>

    Generated by:
    {{ auth()->user()->name }}

</p>

</body>
</html>