import { useEffect } from 'react';
import { usePage } from '@inertiajs/react';

export default function PrintLayout({
    title = 'System Report',
    reportHeading,
    children,
}) {
    const { auth } = usePage().props;

    useEffect(() => {
        window.print();
    }, []);

    return (
        <>
            <title>{title}</title>

            <div className="p-8">

                {/* Company Header */}
                <div className="mb-4 text-center">

                    <h2 className="mb-1 text-2xl font-bold">
                        BizzSoft Inventory Management System
                    </h2>

                    <h4 className="mb-3 text-lg font-semibold uppercase">
                        {reportHeading}
                    </h4>

                    <p className="mb-1">
                        <strong>Printed:</strong>{' '}
                        {new Date().toLocaleString('en-US', {
                            month: 'long',
                            day: '2-digit',
                            year: 'numeric',
                            hour: '2-digit',
                            minute: '2-digit',
                        })}
                    </p>

                </div>


                <hr className="mb-4" />


                {/* Report Content */}
                <main>
                    {children}
                </main>


                <hr className="mt-4" />


                {/* Footer */}
                <div className="flex justify-between text-sm text-gray-500">

                    <small>
                        Generated by: {auth?.user?.name ?? 'System Admin'}
                    </small>

                    <small>
                        Generated on:{' '}
                        {new Date().toLocaleString('en-US', {
                            month: 'long',
                            day: '2-digit',
                            year: 'numeric',
                            hour: '2-digit',
                            minute: '2-digit',
                        })}
                    </small>

                </div>

            </div>
        </>
    );
}